# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Account do
  @moduledoc """
  API calls for all endpoints tagged `Account`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Cancel a pending account deletion.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateAccountCancelDeletionResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_account_cancel_deletion(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateAccountCancelDeletionResponse.t} | {:error, Tesla.Env.t}
  def create_account_cancel_deletion(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/account/cancel-deletion")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateAccountCancelDeletionResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Revoke every browser auth session for this user.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateAccountLogoutAllResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_account_logout_all(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateAccountLogoutAllResponse.t} | {:error, Tesla.Env.t}
  def create_account_logout_all(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/account/logout-all")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateAccountLogoutAllResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Schedule account deletion after a grace period.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateAccountRequestDeletionResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_account_request_deletion(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateAccountRequestDeletionResponse.t} | {:error, Tesla.Env.t}
  def create_account_request_deletion(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/account/request-deletion")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateAccountRequestDeletionResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Revoke all active browser sessions.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteAuthSessionResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_auth_session(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.DeleteAuthSessionResponse.t} | {:error, Tesla.Env.t}
  def delete_auth_session(connection, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/auth/sessions")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteAuthSessionResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Revoke a single browser session by id.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - session_id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteAuthSessionBySessionIdResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_auth_session_by_session_id(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.DeleteAuthSessionBySessionIdResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def delete_auth_session_by_session_id(connection, session_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/auth/sessions/#{session_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteAuthSessionBySessionIdResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Disconnect a third-party app. Its tokens stop working immediately.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - grant_id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteConnectedAppResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_connected_app(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.DeleteConnectedAppResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def delete_connected_app(connection, grant_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/connected-apps/#{grant_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteConnectedAppResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Get the currently-pending deletion request, if any.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetAccountDeletionStatusResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_account_deletion_status(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetAccountDeletionStatusResponse.t} | {:error, Tesla.Env.t}
  def get_account_deletion_status(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/account/deletion-status")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetAccountDeletionStatusResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Identity check — authenticated user + PAT scopes + account state.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.InlineResponse200.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_me(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.InlineResponse200.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def get_me(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/me")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.InlineResponse200{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List active browser auth sessions.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_auth_sessions(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_auth_sessions(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/auth/sessions")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List third-party OAuth apps with access to this account.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_connected_apps(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_connected_apps(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/connected-apps")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
