# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.CompWatchlists do
  @moduledoc """
  API calls for all endpoints tagged `CompWatchlists`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Create a sold-comp watchlist.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateCompWatchlistResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_comp_watchlist(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateCompWatchlistResponse.t} | {:error, Tesla.Env.t}
  def create_comp_watchlist(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/comp-watchlists")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateCompWatchlistResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Manually trigger a watchlist scrape.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateCompWatchlistScrapeResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_comp_watchlist_scrape(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateCompWatchlistScrapeResponse.t} | {:error, Tesla.Env.t}
  def create_comp_watchlist_scrape(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/comp-watchlists/#{id}/scrape")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateCompWatchlistScrapeResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Delete a sold-comp watchlist.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteCompWatchlistResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_comp_watchlist(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.DeleteCompWatchlistResponse.t} | {:error, Tesla.Env.t}
  def delete_comp_watchlist(connection, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/comp-watchlists/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteCompWatchlistResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Recent external sold comps matching this watchlist.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_comp_watchlist_recent(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_comp_watchlist_recent(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/comp-watchlists/#{id}/recent")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List the seller's sold-comp watchlists.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_comp_watchlists(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_comp_watchlists(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/comp-watchlists")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
