# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Customers do
  @moduledoc """
  API calls for all endpoints tagged `Customers`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Bulk blocklist customer handles.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateCustomerBulkDeleteResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_customer_bulk_delete(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateCustomerBulkDeleteResponse.t} | {:error, Tesla.Env.t}
  def create_customer_bulk_delete(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/customers/bulk-delete")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateCustomerBulkDeleteResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Bulk export aggregated customers as CSV.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, String.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_customer_bulk_export(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def create_customer_bulk_export(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/customers/bulk-export")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Get one customer with their recent 50 orders.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - handle (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetCustomerResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_customer(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.GetCustomerResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def get_customer(connection, handle, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/customers/#{handle}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetCustomerResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List aggregated customers (group-by lower(buyer_username)).

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_customers(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_customers(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/customers")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
