# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Inbox do
  @moduledoc """
  API calls for all endpoints tagged `Inbox`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  AI reply suggestion for a conversation.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxAiSuggestResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_ai_suggest(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxAiSuggestResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_ai_suggest(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/ai-suggest")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxAiSuggestResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Create a canned response.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxCannedResponsResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_canned_respons(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxCannedResponsResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_canned_respons(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/canned-responses")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxCannedResponsResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Bulk mark read / mark unread / soft-delete conversations.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxConversationBulkResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_conversation_bulk(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxConversationBulkResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_conversation_bulk(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/conversations/bulk")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxConversationBulkResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  AI reply suggestion for multiple conversations — draft or send.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxConversationBulkAiRespondResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_conversation_bulk_ai_respond(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxConversationBulkAiRespondResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_conversation_bulk_ai_respond(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/conversations/bulk-ai-respond")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxConversationBulkAiRespondResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Accept / counter / decline an active offer on a conversation.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxConversationOfferActionResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_conversation_offer_action(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxConversationOfferActionResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_conversation_offer_action(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/conversations/#{id}/offer-action")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxConversationOfferActionResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Manually re-triage a buyer message.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxMessageTriageResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_message_triage(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxMessageTriageResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_message_triage(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/messages/#{id}/triage")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxMessageTriageResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Accept, counter, or decline an offer on a conversation.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxOfferResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_offer(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxOfferResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_offer(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/#{id}/offer")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxOfferResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Send a reply to a conversation thread.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateInboxReplyResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_inbox_reply(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateInboxReplyResponse.t} | {:error, Tesla.Env.t}
  def create_inbox_reply(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/inbox/#{id}/reply")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateInboxReplyResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Delete a canned response.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteInboxCannedResponsResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_inbox_canned_respons(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.DeleteInboxCannedResponsResponse.t} | {:error, Tesla.Env.t}
  def delete_inbox_canned_respons(connection, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/inbox/canned-responses/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteInboxCannedResponsResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Get one conversation with its messages.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetInboxResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_inbox(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetInboxResponse.t} | {:error, Tesla.Env.t}
  def get_inbox(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/inbox/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetInboxResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List canned responses.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetInboxCannedResponsResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_inbox_canned_respons(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetInboxCannedResponsResponse.t} | {:error, Tesla.Env.t}
  def get_inbox_canned_respons(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/inbox/canned-responses")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetInboxCannedResponsResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Paginated messages for a conversation.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetInboxConversationMessageResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_inbox_conversation_message(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.GetInboxConversationMessageResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def get_inbox_conversation_message(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/inbox/conversations/#{id}/messages")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetInboxConversationMessageResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Sidebar badge: unread conversation count.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetInboxConversationUnreadCountResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_inbox_conversation_unread_count(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetInboxConversationUnreadCountResponse.t} | {:error, Tesla.Env.t}
  def get_inbox_conversation_unread_count(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/inbox/conversations/unread-count")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetInboxConversationUnreadCountResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List conversations.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :page (integer()): 
    - :limit (integer()): 
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_inbox(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_inbox(connection, opts \\ []) do
    optional_params = %{
      :"page" => :query,
      :"limit" => :query
    }
    %{}
    |> method(:get)
    |> url("/v1/inbox")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Update a canned response.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.UpdateInboxCannedResponsResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec update_inbox_canned_respons(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.UpdateInboxCannedResponsResponse.t} | {:error, Tesla.Env.t}
  def update_inbox_canned_respons(connection, id, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/v1/inbox/canned-responses/#{id}")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.UpdateInboxCannedResponsResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Mark read / change status / close conversation.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.UpdateInboxConversationResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec update_inbox_conversation(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.UpdateInboxConversationResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def update_inbox_conversation(connection, id, _opts \\ []) do
    %{}
    |> method(:patch)
    |> url("/v1/inbox/conversations/#{id}")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.UpdateInboxConversationResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
