# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Integrations do
  @moduledoc """
  API calls for all endpoints tagged `Integrations`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Add a Slack/Discord/Webhook destination.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateNotificationIntegrationResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_notification_integration(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateNotificationIntegrationResponse.t} | {:error, Tesla.Env.t}
  def create_notification_integration(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/notification-integrations")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateNotificationIntegrationResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Fire a canned test message to a notification destination.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateNotificationIntegrationTestResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_notification_integration_test(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateNotificationIntegrationTestResponse.t} | {:error, Tesla.Env.t}
  def create_notification_integration_test(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/notification-integrations/#{id}/test")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateNotificationIntegrationTestResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Delete a notification destination.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.DeleteNotificationIntegrationResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_notification_integration(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.DeleteNotificationIntegrationResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def delete_notification_integration(connection, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/v1/notification-integrations/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.DeleteNotificationIntegrationResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List Slack/Discord/Webhook destinations for notify.* automation actions.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_notification_integrations(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_notification_integrations(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/notification-integrations")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Edit a notification destination.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.UpdateNotificationIntegrationResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec update_notification_integration(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.UpdateNotificationIntegrationResponse.t} | {:error, Tesla.Env.t}
  def update_notification_integration(connection, id, _opts \\ []) do
    %{}
    |> method(:patch)
    |> url("/v1/notification-integrations/#{id}")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.UpdateNotificationIntegrationResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
