# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Magic do
  @moduledoc """
  API calls for all endpoints tagged `Magic`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Run a Magic List image scan.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateMagicScanResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_magic_scan(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateMagicScanResponse.t} | {:error, Tesla.Env.t}
  def create_magic_scan(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/magic/scan")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateMagicScanResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Synthesize a draft from confirmed matches.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - run_id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_magic_scan_synthesize(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponse.t} | {:error, Tesla.Env.t}
  def create_magic_scan_synthesize(connection, run_id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/magic/scan/#{run_id}/synthesize")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Get a synthesized Magic List draft.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - draft_id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetMagicDraftResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_magic_draft(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetMagicDraftResponse.t} | {:error, Tesla.Env.t}
  def get_magic_draft(connection, draft_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/magic/drafts/#{draft_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetMagicDraftResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Recent Magic List scans for this seller.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_magic_recent(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_magic_recent(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/magic/recent")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
