# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.RestockPrompts do
  @moduledoc """
  API calls for all endpoints tagged `RestockPrompts`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Dismiss a pending restock prompt.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateRestockPromptDismissResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_restock_prompt_dismiss(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.CreateRestockPromptDismissResponse.t} | {:error, Tesla.Env.t}
  def create_restock_prompt_dismiss(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/restock-prompts/#{id}/dismiss")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateRestockPromptDismissResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Republish a restock prompt to platforms.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.CreateRestockPromptRepublishResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec create_restock_prompt_republish(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.CreateRestockPromptRepublishResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def create_restock_prompt_republish(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/v1/restock-prompts/#{id}/republish")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.CreateRestockPromptRepublishResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  List pending restock prompts.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_restock_prompts(Tesla.Env.client, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_restock_prompts(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/restock-prompts")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
