# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Api.Taxonomy do
  @moduledoc """
  API calls for all endpoints tagged `Taxonomy`.
  """

  alias CrosslySellerAPI.Connection
  import CrosslySellerAPI.RequestBuilder


  @doc """
  Categories for a platform. Default is top-level; pass `?parent=<categoryId>` to drill down one level (supported on cookie platforms whose recipe returns flat parent_id-linked rows).

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - platform (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :parent (String.t): 
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_taxonomy_category(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryResponse.t} | {:error, Tesla.Env.t}
  def get_taxonomy_category(connection, platform, opts \\ []) do
    optional_params = %{
      :"parent" => :query
    }
    %{}
    |> method(:get)
    |> url("/v1/taxonomy/#{platform}/categories")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetTaxonomyCategoryResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Item-specific aspects (eBay) / properties (Etsy) / hard-coded enums (cookie platforms) for a category.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - platform (String.t): 
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryAspectResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_taxonomy_category_aspect(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryAspectResponse.t} | {:error, Tesla.Env.t}
  def get_taxonomy_category_aspect(connection, platform, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/taxonomy/#{platform}/categories/#{id}/aspects")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetTaxonomyCategoryAspectResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Direct children of a category node.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - platform (String.t): 
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryChildrenResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_taxonomy_category_children(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.GetTaxonomyCategoryChildrenResponse.t} | {:ok, CrosslySellerAPI.Model.Error.t} | {:error, Tesla.Env.t}
  def get_taxonomy_category_children(connection, platform, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/v1/taxonomy/#{platform}/categories/#{id}/children")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetTaxonomyCategoryChildrenResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Normalized field schema the seller needs to fill before crossposting to this platform. Combines master fields (title/description/price/condition) with platform-specific overrides.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - platform (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :category_id (String.t): Optional — used to inline aspects when present.
  ## Returns

  {:ok, CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_taxonomy_required_field(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponse.t} | {:error, Tesla.Env.t}
  def get_taxonomy_required_field(connection, platform, opts \\ []) do
    optional_params = %{
      :"categoryId" => :query
    }
    %{}
    |> method(:get)
    |> url("/v1/taxonomy/#{platform}/required-fields")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponse{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end

  @doc """
  Reverse lookup — suggest categories matching a search phrase. eBay-only today.

  ## Parameters

  - connection (CrosslySellerAPI.Connection): Connection to server
  - platform (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :q (String.t): 
  ## Returns

  {:ok, V1List} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec list_taxonomy_suggest(Tesla.Env.client, String.t, keyword()) :: {:ok, CrosslySellerAPI.Model.Error.t} | {:ok, CrosslySellerAPI.Model.V1List.t} | {:error, Tesla.Env.t}
  def list_taxonomy_suggest(connection, platform, opts \\ []) do
    optional_params = %{
      :"q" => :query
    }
    %{}
    |> method(:get)
    |> url("/v1/taxonomy/#{platform}/suggest")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %CrosslySellerAPI.Model.V1List{}},
      { 400, %CrosslySellerAPI.Model.Error{}},
      { 401, %CrosslySellerAPI.Model.Error{}},
      { 403, %CrosslySellerAPI.Model.Error{}},
      { 404, %CrosslySellerAPI.Model.Error{}},
      { 429, %CrosslySellerAPI.Model.Error{}},
      { 500, %CrosslySellerAPI.Model.Error{}}
    ])
  end
end
