# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateMagicScanSynthesizeResponsePayloadDimensions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"lengthIn",
    :"widthIn",
    :"heightIn"
  ]

  @type t :: %__MODULE__{
    :"lengthIn" => float() | nil,
    :"widthIn" => float() | nil,
    :"heightIn" => float() | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateMagicScanSynthesizeResponsePayloadDimensions do
  def decode(value, _options) do
    value
  end
end

