# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxDisbursementRuleResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ruleId",
    :"isActive"
  ]

  @type t :: %__MODULE__{
    :"ruleId" => String.t,
    :"isActive" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxDisbursementRuleResponse do
  def decode(value, _options) do
    value
  end
end

