# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateAiCategorizeFromImageResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"category",
    :"subCategory",
    :"brand",
    :"condition",
    :"colors",
    :"size",
    :"tags",
    :"suggestedTitle",
    :"material",
    :"style",
    :"pattern",
    :"department",
    :"gender",
    :"itemType",
    :"sizeSystem"
  ]

  @type t :: %__MODULE__{
    :"category" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"subCategory" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"brand" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"condition" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"colors" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseColors.t | nil,
    :"size" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"tags" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseColors.t | nil,
    :"suggestedTitle" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"material" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"style" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"pattern" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"department" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"gender" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"itemType" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"sizeSystem" => CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateAiCategorizeFromImageResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"category", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"subCategory", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"brand", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"condition", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"colors", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseColors, options)
    |> deserialize(:"size", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"tags", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseColors, options)
    |> deserialize(:"suggestedTitle", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"material", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"style", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"pattern", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"department", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"gender", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"itemType", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"sizeSystem", :struct, CrosslyBuyerAPI.Model.CreateAiGenerateListingResponseDescription, options)
  end
end

