# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreatePlatformAccountConnectResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"accountId",
    :"needsFirstSync"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"accountId" => String.t,
    :"needsFirstSync" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreatePlatformAccountConnectResponse do
  def decode(value, _options) do
    value
  end
end

