# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxCampaignPreviewResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"recipientCount",
    :"totalBaseUnits",
    :"poolBalanceBaseUnits",
    :"hash",
    :"allocations",
    :"allocationsTruncated"
  ]

  @type t :: %__MODULE__{
    :"recipientCount" => float(),
    :"totalBaseUnits" => String.t,
    :"poolBalanceBaseUnits" => String.t,
    :"hash" => String.t,
    :"allocations" => [CrosslyBuyerAPI.Model.CreateCbxCampaignPreviewResponseAllocations.t],
    :"allocationsTruncated" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxCampaignPreviewResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"allocations", :list, CrosslyBuyerAPI.Model.CreateCbxCampaignPreviewResponseAllocations, options)
  end
end

