# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateInventoryBulkQuantityResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"affected",
    :"skipped",
    :"bulkJobId"
  ]

  @type t :: %__MODULE__{
    :"affected" => float(),
    :"skipped" => float(),
    :"bulkJobId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateInventoryBulkQuantityResponse do
  def decode(value, _options) do
    value
  end
end

