# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxSubjectStakeResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"stakeId",
    :"tierSlug",
    :"baseUnits",
    :"feeDiscountBps",
    :"earnBoostBps"
  ]

  @type t :: %__MODULE__{
    :"stakeId" => String.t,
    :"tierSlug" => String.t,
    :"baseUnits" => String.t,
    :"feeDiscountBps" => float(),
    :"earnBoostBps" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxSubjectStakeResponse do
  def decode(value, _options) do
    value
  end
end

