# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateBuyerCartQuoteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"kind",
    :"taxCents",
    :"shippingCents",
    :"totalCents",
    :"currency",
    :"itemsTotalCents",
    :"pickupCartItemIds",
    :"taxComplete"
  ]

  @type t :: %__MODULE__{
    :"kind" => String.t,
    :"taxCents" => float(),
    :"shippingCents" => float(),
    :"totalCents" => float(),
    :"currency" => String.t,
    :"itemsTotalCents" => float(),
    :"pickupCartItemIds" => [String.t],
    :"taxComplete" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateBuyerCartQuoteResponse do
  def decode(value, _options) do
    value
  end
end

