# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateBuyerOfferResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ok",
    :"offer"
  ]

  @type t :: %__MODULE__{
    :"ok" => boolean(),
    :"offer" => CrosslyBuyerAPI.Model.CreateBuyerOfferResponseDataOffer.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateBuyerOfferResponseData do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"offer", :struct, CrosslyBuyerAPI.Model.CreateBuyerOfferResponseDataOffer, options)
  end
end

