# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateMagicScanSynthesizeResponsePayloadGrading do
  @moduledoc """
  Third-party grading read off a slab label, when the item is one.    SEPARATE FROM `condition` and never derived from it. A grade is a claim  about what a grading company certified; inferring \"PSA 10\" from a coarse  condition would be inventing an authenticity claim. It is equally never  filled from our own vision estimate (`bulk_market_items.grade`), which  ships with an explicit \"not a professional grade\" disclaimer.    Feeds eBay's Professional Grader / Grade / Certification Number condition  descriptors (synthesize/condition-descriptors.ts) and, on platforms with  no grading field, the title.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"graderSlug",
    :"grade",
    :"qualifier",
    :"sealGrade",
    :"certNumber",
    :"gradeKey",
    :"verifiedAt"
  ]

  @type t :: %__MODULE__{
    :"graderSlug" => String.t,
    :"grade" => String.t,
    :"qualifier" => String.t | nil,
    :"sealGrade" => String.t | nil,
    :"certNumber" => String.t | nil,
    :"gradeKey" => String.t,
    :"verifiedAt" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateMagicScanSynthesizeResponsePayloadGrading do
  def decode(value, _options) do
    value
  end
end

