# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"created",
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"created" => [CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponseCreated.t],
    :"errors" => [CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponseErrors.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"created", :list, CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponseCreated, options)
    |> deserialize(:"errors", :list, CrosslyBuyerAPI.Model.CreateAutomationRuleImportResponseErrors, options)
  end
end

