# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxDisbursementRuleCheckResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"outcome",
    :"fired",
    :"poolBaseUnits",
    :"thresholdBaseUnits",
    :"distributeBaseUnits",
    :"coverageBps",
    :"campaignId"
  ]

  @type t :: %__MODULE__{
    :"outcome" => String.t,
    :"fired" => boolean(),
    :"poolBaseUnits" => String.t,
    :"thresholdBaseUnits" => String.t,
    :"distributeBaseUnits" => String.t,
    :"coverageBps" => float() | nil,
    :"campaignId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxDisbursementRuleCheckResponse do
  def decode(value, _options) do
    value
  end
end

