# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateBuyerIdentifyResponseHudFacts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"label",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"label" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateBuyerIdentifyResponseHudFacts do
  def decode(value, _options) do
    value
  end
end

