# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxAccrualReverseResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reversed"
  ]

  @type t :: %__MODULE__{
    :"reversed" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxAccrualReverseResponse do
  def decode(value, _options) do
    value
  end
end

