# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxSubjectSpendPlanResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"legs",
    :"shortfallBaseUnits",
    :"fullyFunded"
  ]

  @type t :: %__MODULE__{
    :"legs" => [CrosslyBuyerAPI.Model.CreateCbxSubjectSpendPlanResponseLegs.t],
    :"shortfallBaseUnits" => String.t,
    :"fullyFunded" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxSubjectSpendPlanResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"legs", :list, CrosslyBuyerAPI.Model.CreateCbxSubjectSpendPlanResponseLegs, options)
  end
end

