# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxRevenueSweepResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"swept",
    :"baseUnits",
    :"txSig",
    :"reason",
    :"breakdown"
  ]

  @type t :: %__MODULE__{
    :"swept" => boolean(),
    :"baseUnits" => String.t,
    :"txSig" => String.t | nil,
    :"reason" => String.t | nil,
    :"breakdown" => CrosslyBuyerAPI.Model.CreateCbxRevenueSweepResponseBreakdown.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxRevenueSweepResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"breakdown", :struct, CrosslyBuyerAPI.Model.CreateCbxRevenueSweepResponseBreakdown, options)
  end
end

