# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateListingDiscrepancyResolveResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ok",
    :"bulkJobId"
  ]

  @type t :: %__MODULE__{
    :"ok" => boolean(),
    :"bulkJobId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateListingDiscrepancyResolveResponse do
  def decode(value, _options) do
    value
  end
end

