# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateAiEnhanceListingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"title",
    :"description",
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"title" => String.t,
    :"description" => String.t,
    :"tags" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateAiEnhanceListingResponse do
  def decode(value, _options) do
    value
  end
end

