# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateListingMagicFillResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"filled",
    :"count",
    :"aiAvailable"
  ]

  @type t :: %__MODULE__{
    :"filled" => map(),
    :"count" => float(),
    :"aiAvailable" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateListingMagicFillResponse do
  def decode(value, _options) do
    value
  end
end

