# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateAdOffsiteCampaignResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"campaignId",
    :"network",
    :"status",
    :"creativeHeadline",
    :"dailyBudgetCents"
  ]

  @type t :: %__MODULE__{
    :"campaignId" => String.t,
    :"network" => String.t,
    :"status" => String.t,
    :"creativeHeadline" => String.t | nil,
    :"dailyBudgetCents" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateAdOffsiteCampaignResponse do
  def decode(value, _options) do
    value
  end
end

