# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxSubjectGrantResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"grantId",
    :"duplicate"
  ]

  @type t :: %__MODULE__{
    :"grantId" => String.t | nil,
    :"duplicate" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxSubjectGrantResponse do
  def decode(value, _options) do
    value
  end
end

