# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateRestockPromptRepublishResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message",
    :"platforms",
    :"remainingPlatforms",
    :"jobIds",
    :"bulkJobId"
  ]

  @type t :: %__MODULE__{
    :"message" => String.t,
    :"platforms" => [String.t],
    :"remainingPlatforms" => [String.t],
    :"jobIds" => [String.t],
    :"bulkJobId" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateRestockPromptRepublishResponse do
  def decode(value, _options) do
    value
  end
end

