# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateBuyerOfferResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data"
  ]

  @type t :: %__MODULE__{
    :"data" => CrosslyBuyerAPI.Model.CreateBuyerOfferResponseData.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateBuyerOfferResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, CrosslyBuyerAPI.Model.CreateBuyerOfferResponseData, options)
  end
end

