# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateMagicScanResponseEbayMatch do
  @moduledoc """
  Top eBay match (or null when eBay returned zero). Drives the  synthesize step's title/brand/price seed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemId",
    :"legacyItemId",
    :"title",
    :"brand",
    :"priceCents",
    :"currency",
    :"condition",
    :"categoryId",
    :"categoryPath",
    :"itemUrl",
    :"thumbnailUrl",
    :"aspects"
  ]

  @type t :: %__MODULE__{
    :"itemId" => String.t,
    :"legacyItemId" => String.t | nil,
    :"title" => String.t,
    :"brand" => String.t | nil,
    :"priceCents" => float() | nil,
    :"currency" => String.t | nil,
    :"condition" => String.t | nil,
    :"categoryId" => String.t | nil,
    :"categoryPath" => String.t | nil,
    :"itemUrl" => String.t,
    :"thumbnailUrl" => String.t | nil,
    :"aspects" => map() | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateMagicScanResponseEbayMatch do
  def decode(value, _options) do
    value
  end
end

