# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateOrderDisputeResponseError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"code"
  ]

  @type t :: %__MODULE__{
    :"code" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateOrderDisputeResponseError do
  def decode(value, _options) do
    value
  end
end

