# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCbxCreditRepayResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"appliedCents",
    :"remainingCents",
    :"duplicate"
  ]

  @type t :: %__MODULE__{
    :"appliedCents" => float(),
    :"remainingCents" => float(),
    :"duplicate" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCbxCreditRepayResponse do
  def decode(value, _options) do
    value
  end
end

