# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateOrderBulkMarkShippedResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"updated",
    :"skipped"
  ]

  @type t :: %__MODULE__{
    :"updated" => float(),
    :"skipped" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateOrderBulkMarkShippedResponse do
  def decode(value, _options) do
    value
  end
end

