# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.CreateCompWatchlistResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"brand",
    :"name",
    :"createdAt",
    :"userId",
    :"condition",
    :"categoryMain",
    :"platform",
    :"minPrice",
    :"maxPrice",
    :"lastMatchedAt",
    :"lastScrapedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"brand" => String.t | nil,
    :"name" => String.t,
    :"createdAt" => DateTime.t,
    :"userId" => String.t,
    :"condition" => String.t | nil,
    :"categoryMain" => String.t | nil,
    :"platform" => String.t | nil,
    :"minPrice" => String.t | nil,
    :"maxPrice" => String.t | nil,
    :"lastMatchedAt" => DateTime.t | nil,
    :"lastScrapedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.CreateCompWatchlistResponse do
  def decode(value, _options) do
    value
  end
end

