# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.DeleteInboxCannedResponsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"error"
  ]

  @type t :: %__MODULE__{
    :"error" => CrosslyBuyerAPI.Model.CreateOrderDisputeResponseError.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.DeleteInboxCannedResponsResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"error", :struct, CrosslyBuyerAPI.Model.CreateOrderDisputeResponseError, options)
  end
end

