# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.DeleteListingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"jobs"
  ]

  @type t :: %__MODULE__{
    :"jobs" => [CrosslyBuyerAPI.Model.CreateListingResponseJobs.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.DeleteListingResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"jobs", :list, CrosslyBuyerAPI.Model.CreateListingResponseJobs, options)
  end
end

