# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetTaxScheduleCResponseCounts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sales",
    :"refunds",
    :"mileageEntries"
  ]

  @type t :: %__MODULE__{
    :"sales" => float(),
    :"refunds" => float(),
    :"mileageEntries" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetTaxScheduleCResponseCounts do
  def decode(value, _options) do
    value
  end
end

