# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetTaxonomyCategoryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categories"
  ]

  @type t :: %__MODULE__{
    :"categories" => [CrosslyBuyerAPI.Model.GetTaxonomyCategoryResponseCategories.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetTaxonomyCategoryResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"categories", :list, CrosslyBuyerAPI.Model.GetTaxonomyCategoryResponseCategories, options)
  end
end

