# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetTaxScheduleCResponseExpenses do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platformFees",
    :"shippingExpenses",
    :"costOfGoodsSold",
    :"carAndTruckMileage",
    :"carAndTruckMiles"
  ]

  @type t :: %__MODULE__{
    :"platformFees" => float(),
    :"shippingExpenses" => float(),
    :"costOfGoodsSold" => float(),
    :"carAndTruckMileage" => float(),
    :"carAndTruckMiles" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetTaxScheduleCResponseExpenses do
  def decode(value, _options) do
    value
  end
end

