# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAutomationCatalogResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"triggerTypes",
    :"actionTypes",
    :"conditionTypes"
  ]

  @type t :: %__MODULE__{
    :"triggerTypes" => [CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes.t],
    :"actionTypes" => [CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes.t],
    :"conditionTypes" => [CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAutomationCatalogResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"triggerTypes", :list, CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes, options)
    |> deserialize(:"actionTypes", :list, CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes, options)
    |> deserialize(:"conditionTypes", :list, CrosslyBuyerAPI.Model.GetAutomationCatalogResponseTriggerTypes, options)
  end
end

