# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSellThrough do
  @moduledoc """
  The context the bare rate can't carry. `tooYoungToJudge` is the  important one: a cohort measured the day its window closed has had no  time to sell, and a low number there means \"wait\", not \"bad buys\" — a  seller acting on it would stop sourcing for no reason.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rate",
    :"cohortSize",
    :"cohortSold",
    :"maturityDays",
    :"tooYoungToJudge"
  ]

  @type t :: %__MODULE__{
    :"rate" => float() | nil,
    :"cohortSize" => float(),
    :"cohortSold" => float(),
    :"maturityDays" => float(),
    :"tooYoungToJudge" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSellThrough do
  def decode(value, _options) do
    value
  end
end

