# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"brands",
    :"conditions",
    :"categories"
  ]

  @type t :: %__MODULE__{
    :"brands" => [CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands.t],
    :"conditions" => [CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands.t],
    :"categories" => [CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"brands", :list, CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands, options)
    |> deserialize(:"conditions", :list, CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands, options)
    |> deserialize(:"categories", :list, CrosslyBuyerAPI.Model.GetBuyerCatalogFacetResponseBrands, options)
  end
end

