# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetMarketVariantBookResponseBids do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"priceCents",
    :"count"
  ]

  @type t :: %__MODULE__{
    :"priceCents" => float(),
    :"count" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetMarketVariantBookResponseBids do
  def decode(value, _options) do
    value
  end
end

