# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAnalyticTodayResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"checklist",
    :"streak",
    :"activitySparkline"
  ]

  @type t :: %__MODULE__{
    :"checklist" => CrosslyBuyerAPI.Model.GetAnalyticTodayResponseChecklist.t,
    :"streak" => CrosslyBuyerAPI.Model.GetAnalyticTodayResponseStreak.t,
    :"activitySparkline" => [float()]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAnalyticTodayResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"checklist", :struct, CrosslyBuyerAPI.Model.GetAnalyticTodayResponseChecklist, options)
    |> deserialize(:"streak", :struct, CrosslyBuyerAPI.Model.GetAnalyticTodayResponseStreak, options)
  end
end

