# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAiProviderResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"providers"
  ]

  @type t :: %__MODULE__{
    :"providers" => [CrosslyBuyerAPI.Model.GetAiProviderResponseProviders.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAiProviderResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"providers", :list, CrosslyBuyerAPI.Model.GetAiProviderResponseProviders, options)
  end
end

