# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetBuyerPreferenceResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"retailers",
    :"brands",
    :"priceBand",
    :"matchRate",
    :"observations"
  ]

  @type t :: %__MODULE__{
    :"retailers" => [CrosslyBuyerAPI.Model.GetBuyerPreferenceResponseRetailers.t],
    :"brands" => [CrosslyBuyerAPI.Model.GetBuyerPreferenceResponseBrands.t],
    :"priceBand" => CrosslyBuyerAPI.Model.GetBuyerPreferenceResponsePriceBand.t | nil,
    :"matchRate" => float() | nil,
    :"observations" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetBuyerPreferenceResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"retailers", :list, CrosslyBuyerAPI.Model.GetBuyerPreferenceResponseRetailers, options)
    |> deserialize(:"brands", :list, CrosslyBuyerAPI.Model.GetBuyerPreferenceResponseBrands, options)
    |> deserialize(:"priceBand", :struct, CrosslyBuyerAPI.Model.GetBuyerPreferenceResponsePriceBand, options)
  end
end

