# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetSpatialPublicResponseSolvedContainers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"index",
    :"label",
    :"groupPath",
    :"capacity",
    :"used"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"index" => float(),
    :"label" => String.t,
    :"groupPath" => [String.t],
    :"capacity" => float(),
    :"used" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetSpatialPublicResponseSolvedContainers do
  def decode(value, _options) do
    value
  end
end

