# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetCbxMeResponseTerms do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"earnRateBps",
    :"purchaseMaturationDays",
    :"claimMinCents",
    :"withdrawalFeeBps",
    :"withdrawalFeeMinCents",
    :"withdrawalFeeMaxCents",
    :"inactivityExpiryDays",
    :"claimsEnabled"
  ]

  @type t :: %__MODULE__{
    :"earnRateBps" => float(),
    :"purchaseMaturationDays" => float(),
    :"claimMinCents" => float(),
    :"withdrawalFeeBps" => float(),
    :"withdrawalFeeMinCents" => float(),
    :"withdrawalFeeMaxCents" => float(),
    :"inactivityExpiryDays" => float(),
    :"claimsEnabled" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetCbxMeResponseTerms do
  def decode(value, _options) do
    value
  end
end

