# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAnalyticDashboardResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"revenue",
    :"profit",
    :"soldItemsCount",
    :"cancelledCount",
    :"cancelRate",
    :"refundedAmount",
    :"refundedCount",
    :"listedItemsCount",
    :"avgSalePrice",
    :"sellThroughRate",
    :"sellThrough",
    :"avgDaysToSell",
    :"salesByPlatform",
    :"avgSalePriceByPlatform",
    :"revenueByDay",
    :"topCategories",
    :"topSubcategories",
    :"topBrands",
    :"top5ItemsByRevenue",
    :"recentSales",
    :"availableLabels"
  ]

  @type t :: %__MODULE__{
    :"revenue" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"profit" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"soldItemsCount" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"cancelledCount" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"cancelRate" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseCancelRate.t,
    :"refundedAmount" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"refundedCount" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"listedItemsCount" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"avgSalePrice" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue.t,
    :"sellThroughRate" => float() | nil,
    :"sellThrough" => CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSellThrough.t,
    :"avgDaysToSell" => float() | nil,
    :"salesByPlatform" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSalesByPlatform.t],
    :"avgSalePriceByPlatform" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseAvgSalePriceByPlatform.t],
    :"revenueByDay" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenueByDay.t],
    :"topCategories" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories.t],
    :"topSubcategories" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories.t],
    :"topBrands" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories.t],
    :"top5ItemsByRevenue" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTop5ItemsByRevenue.t],
    :"recentSales" => [CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRecentSales.t],
    :"availableLabels" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAnalyticDashboardResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"revenue", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"profit", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"soldItemsCount", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"cancelledCount", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"cancelRate", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseCancelRate, options)
    |> deserialize(:"refundedAmount", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"refundedCount", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"listedItemsCount", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"avgSalePrice", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenue, options)
    |> deserialize(:"sellThrough", :struct, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSellThrough, options)
    |> deserialize(:"salesByPlatform", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseSalesByPlatform, options)
    |> deserialize(:"avgSalePriceByPlatform", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseAvgSalePriceByPlatform, options)
    |> deserialize(:"revenueByDay", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRevenueByDay, options)
    |> deserialize(:"topCategories", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories, options)
    |> deserialize(:"topSubcategories", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories, options)
    |> deserialize(:"topBrands", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTopCategories, options)
    |> deserialize(:"top5ItemsByRevenue", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseTop5ItemsByRevenue, options)
    |> deserialize(:"recentSales", :list, CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseRecentSales, options)
  end
end

