# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetActionLogFacetResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platforms",
    :"actions",
    :"categories"
  ]

  @type t :: %__MODULE__{
    :"platforms" => [String.t],
    :"actions" => [String.t],
    :"categories" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetActionLogFacetResponse do
  def decode(value, _options) do
    value
  end
end

