# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseAvgSalePriceByPlatform do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platform",
    :"avgPrice",
    :"count"
  ]

  @type t :: %__MODULE__{
    :"platform" => String.t,
    :"avgPrice" => float(),
    :"count" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAnalyticDashboardResponseAvgSalePriceByPlatform do
  def decode(value, _options) do
    value
  end
end

