# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetConnectionExtensionOnlineResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"online"
  ]

  @type t :: %__MODULE__{
    :"online" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetConnectionExtensionOnlineResponse do
  def decode(value, _options) do
    value
  end
end

