# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetVariationGroupPublishPlanResponsePlans do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platform",
    :"mode",
    :"listingsProduced",
    :"explanation"
  ]

  @type t :: %__MODULE__{
    :"platform" => String.t,
    :"mode" => String.t,
    :"listingsProduced" => float(),
    :"explanation" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetVariationGroupPublishPlanResponsePlans do
  def decode(value, _options) do
    value
  end
end

