# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetAdOffsiteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"maxOffsiteShareBps",
    :"minReturnBps",
    :"returnWindowDays",
    :"allowedNetworks",
    :"autoPausedAt",
    :"autoPausedReason",
    :"optedInAt",
    :"terms",
    :"networkWired"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean(),
    :"maxOffsiteShareBps" => float() | nil,
    :"minReturnBps" => float() | nil,
    :"returnWindowDays" => float() | nil,
    :"allowedNetworks" => [String.t] | nil,
    :"autoPausedAt" => String.t | nil,
    :"autoPausedReason" => String.t | nil,
    :"optedInAt" => String.t | nil,
    :"terms" => CrosslyBuyerAPI.Model.GetAdOffsiteResponseTerms.t,
    :"networkWired" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetAdOffsiteResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"terms", :struct, CrosslyBuyerAPI.Model.GetAdOffsiteResponseTerms, options)
  end
end

