# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetSpatialSceneResponseSize do
  @moduledoc """
  Real dimensions when the catalog knows them. Else the profile default.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"x",
    :"y",
    :"z"
  ]

  @type t :: %__MODULE__{
    :"x" => float(),
    :"y" => float(),
    :"z" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetSpatialSceneResponseSize do
  def decode(value, _options) do
    value
  end
end

