# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetMeTemplateSuggestResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"template"
  ]

  @type t :: %__MODULE__{
    :"template" => Null
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetMeTemplateSuggestResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"template", :struct, CrosslyBuyerAPI.Model.Null, options)
  end
end

