# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetSpatialPublicResponseSolvedPlacements do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemId",
    :"unitId",
    :"containerKey",
    :"containerIndex",
    :"slotIndex",
    :"position",
    :"groupPath",
    :"pinned"
  ]

  @type t :: %__MODULE__{
    :"itemId" => String.t,
    :"unitId" => String.t | nil,
    :"containerKey" => String.t,
    :"containerIndex" => float(),
    :"slotIndex" => float(),
    :"position" => map(),
    :"groupPath" => [String.t],
    :"pinned" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetSpatialPublicResponseSolvedPlacements do
  def decode(value, _options) do
    value
  end
end

