# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetInboxConversationMessageResponseMessages do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"conversationId",
    :"platformMessageId",
    :"sender",
    :"body",
    :"attachments",
    :"sentAt",
    :"syncedAt",
    :"aiIntent",
    :"aiUrgency",
    :"aiScamScore",
    :"aiSuggestedReply",
    :"aiTriagedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"conversationId" => String.t,
    :"platformMessageId" => String.t | nil,
    :"sender" => String.t,
    :"body" => String.t | nil,
    :"attachments" => [String.t] | nil,
    :"sentAt" => DateTime.t,
    :"syncedAt" => DateTime.t | nil,
    :"aiIntent" => String.t | nil,
    :"aiUrgency" => String.t | nil,
    :"aiScamScore" => float() | nil,
    :"aiSuggestedReply" => String.t | nil,
    :"aiTriagedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetInboxConversationMessageResponseMessages do
  def decode(value, _options) do
    value
  end
end

