# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetOauthInitResponseOneOf3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"requestUrl",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"requestUrl" => String.t,
    :"message" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetOauthInitResponseOneOf3 do
  def decode(value, _options) do
    value
  end
end

