# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetInventoryLabelStatResponseLabels do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"label",
    :"itemCount",
    :"color"
  ]

  @type t :: %__MODULE__{
    :"label" => String.t,
    :"itemCount" => float(),
    :"color" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetInventoryLabelStatResponseLabels do
  def decode(value, _options) do
    value
  end
end

