# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.GetBuyerProfileResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"email",
    :"displayName",
    :"shippingAddress",
    :"bucksBalanceCents"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"email" => String.t,
    :"displayName" => String.t | nil,
    :"shippingAddress" => map() | nil,
    :"bucksBalanceCents" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.GetBuyerProfileResponse do
  def decode(value, _options) do
    value
  end
end

