# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.InlineObject4 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"namespace",
    :"value",
    :"retailHost",
    :"pagePriceCents",
    :"pageCurrency"
  ]

  @type t :: %__MODULE__{
    :"namespace" => String.t,
    :"value" => String.t,
    :"retailHost" => String.t | nil,
    :"pagePriceCents" => integer() | nil,
    :"pageCurrency" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.InlineObject4 do
  def decode(value, _options) do
    value
  end
end

