# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListCbxStakeTiersItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"label",
    :"minBaseUnits",
    :"feeDiscountBps",
    :"earnBoostBps",
    :"cooldownDays"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"label" => String.t,
    :"minBaseUnits" => String.t,
    :"feeDiscountBps" => float(),
    :"earnBoostBps" => float(),
    :"cooldownDays" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListCbxStakeTiersItem do
  def decode(value, _options) do
    value
  end
end

