# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListSpatialScenesItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"kind",
    :"name",
    :"categorySlug",
    :"visibility",
    :"publicSlug",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"kind" => String.t,
    :"name" => String.t,
    :"categorySlug" => String.t | nil,
    :"visibility" => String.t,
    :"publicSlug" => String.t | nil,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListSpatialScenesItem do
  def decode(value, _options) do
    value
  end
end

