# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListMobilePushTokensItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"token",
    :"platform",
    :"createdAt",
    :"lastUsedAt"
  ]

  @type t :: %__MODULE__{
    :"token" => String.t,
    :"platform" => String.t,
    :"createdAt" => DateTime.t,
    :"lastUsedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListMobilePushTokensItem do
  def decode(value, _options) do
    value
  end
end

