# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListBuyerScanSessionsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"device",
    :"label",
    :"startedAt",
    :"endedAt",
    :"captureCount",
    :"live"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"device" => String.t,
    :"label" => String.t | nil,
    :"startedAt" => String.t,
    :"endedAt" => String.t | nil,
    :"captureCount" => float(),
    :"live" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListBuyerScanSessionsItem do
  def decode(value, _options) do
    value
  end
end

