# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListBuyerWishlistsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListBuyerWishlistsItem do
  def decode(value, _options) do
    value
  end
end

