# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListCbxRedemptionServicesItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"serviceKind",
    :"label"
  ]

  @type t :: %__MODULE__{
    :"serviceKind" => String.t,
    :"label" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListCbxRedemptionServicesItem do
  def decode(value, _options) do
    value
  end
end

