# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListInventoryItemCategory do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"main",
    :"sub"
  ]

  @type t :: %__MODULE__{
    :"main" => String.t | nil,
    :"sub" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListInventoryItemCategory do
  def decode(value, _options) do
    value
  end
end

