# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListRestockPromptsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"listingId",
    :"inventoryItemId",
    :"platforms",
    :"newQuantity",
    :"createdAt",
    :"listingTitle",
    :"listingImages",
    :"listingPrice"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"listingId" => String.t,
    :"inventoryItemId" => String.t | nil,
    :"platforms" => [String.t],
    :"newQuantity" => float(),
    :"createdAt" => DateTime.t,
    :"listingTitle" => String.t | nil,
    :"listingImages" => [String.t] | nil,
    :"listingPrice" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListRestockPromptsItem do
  def decode(value, _options) do
    value
  end
end

