# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListCbxBoostsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"targetKind",
    :"targetValue",
    :"boostedRateBps",
    :"budgetCents",
    :"spentCents",
    :"remainingCents",
    :"startsAt",
    :"endsAt",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"targetKind" => String.t,
    :"targetValue" => String.t | nil,
    :"boostedRateBps" => float(),
    :"budgetCents" => float(),
    :"spentCents" => float(),
    :"remainingCents" => float(),
    :"startsAt" => String.t,
    :"endsAt" => String.t,
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListCbxBoostsItem do
  def decode(value, _options) do
    value
  end
end

