# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListTaxonomySuggestItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"externalId",
    :"display",
    :"level",
    :"catalog",
    :"breadcrumb",
    :"displays"
  ]

  @type t :: %__MODULE__{
    :"externalId" => String.t,
    :"display" => String.t,
    :"level" => float(),
    :"catalog" => CrosslyBuyerAPI.Model.ListTaxonomySuggestItemCatalog.t,
    :"breadcrumb" => String.t,
    :"displays" => CrosslyBuyerAPI.Model.ListTaxonomySuggestItemDisplays.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListTaxonomySuggestItem do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"catalog", :struct, CrosslyBuyerAPI.Model.ListTaxonomySuggestItemCatalog, options)
    |> deserialize(:"displays", :struct, CrosslyBuyerAPI.Model.ListTaxonomySuggestItemDisplays, options)
  end
end

