# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListImportsItemFilters do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"listedAfter",
    :"listedBefore",
    :"minPrice",
    :"maxPrice",
    :"conditionIncludes",
    :"maxImport"
  ]

  @type t :: %__MODULE__{
    :"listedAfter" => String.t | nil,
    :"listedBefore" => String.t | nil,
    :"minPrice" => float() | nil,
    :"maxPrice" => float() | nil,
    :"conditionIncludes" => [String.t] | nil,
    :"maxImport" => float() | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListImportsItemFilters do
  def decode(value, _options) do
    value
  end
end

