# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.ListPayoutCompareItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platform",
    :"grossCents",
    :"feeCents",
    :"feeSource",
    :"shippingCents",
    :"shippingSource",
    :"netCents",
    :"takeHomePct",
    :"assumptions"
  ]

  @type t :: %__MODULE__{
    :"platform" => String.t,
    :"grossCents" => float(),
    :"feeCents" => float(),
    :"feeSource" => String.t,
    :"shippingCents" => float(),
    :"shippingSource" => String.t,
    :"netCents" => float(),
    :"takeHomePct" => float(),
    :"assumptions" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.ListPayoutCompareItem do
  def decode(value, _options) do
    value
  end
end

