# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.UpdateInventoryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"category"
  ]

  @type t :: %__MODULE__{
    :"category" => CrosslyBuyerAPI.Model.ListInventoryItemCategory.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.UpdateInventoryResponse do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"category", :struct, CrosslyBuyerAPI.Model.ListInventoryItemCategory, options)
  end
end

