# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.UpdateBuyerCheckoutControlResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"patId",
    :"enabled",
    :"dailyLimitCents",
    :"perOrderLimitCents",
    :"maxUnitsPerListingPerDay"
  ]

  @type t :: %__MODULE__{
    :"patId" => String.t,
    :"enabled" => boolean(),
    :"dailyLimitCents" => float(),
    :"perOrderLimitCents" => float(),
    :"maxUnitsPerListingPerDay" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.UpdateBuyerCheckoutControlResponse do
  def decode(value, _options) do
    value
  end
end

