# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.UpdateMileageResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"miles",
    :"id",
    :"userId",
    :"date",
    :"purpose",
    :"startLocation",
    :"endLocation",
    :"notes",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"miles" => float(),
    :"id" => String.t,
    :"userId" => String.t,
    :"date" => String.t,
    :"purpose" => String.t,
    :"startLocation" => String.t | nil,
    :"endLocation" => String.t | nil,
    :"notes" => String.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.UpdateMileageResponse do
  def decode(value, _options) do
    value
  end
end

