# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.UpdateAdOffsiteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"maxOffsiteShareBps",
    :"minReturnBps",
    :"returnWindowDays"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean(),
    :"maxOffsiteShareBps" => float(),
    :"minReturnBps" => float(),
    :"returnWindowDays" => float()
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.UpdateAdOffsiteResponse do
  def decode(value, _options) do
    value
  end
end

