# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslyBuyerAPI.Model.V1List do
  @moduledoc """
  The canonical collection envelope. The array is ALWAYS under `data`, never under the noun — so one accessor works for every list endpoint.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"pagination",
    :"meta"
  ]

  @type t :: %__MODULE__{
    :"data" => [AnyType],
    :"pagination" => CrosslyBuyerAPI.Model.Pagination.t | nil,
    :"meta" => %{optional(String.t) => map()} | nil
  }
end

defimpl Poison.Decoder, for: CrosslyBuyerAPI.Model.V1List do
  import CrosslyBuyerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, CrosslyBuyerAPI.Model.AnyType, options)
    |> deserialize(:"pagination", :struct, CrosslyBuyerAPI.Model.Pagination, options)
  end
end

