# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAutomationRuleImportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"created",
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"created" => [CrosslySellerAPI.Model.CreateAutomationRuleImportResponseCreated.t],
    :"errors" => [CrosslySellerAPI.Model.CreateAutomationRuleImportResponseErrors.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAutomationRuleImportResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"created", :list, CrosslySellerAPI.Model.CreateAutomationRuleImportResponseCreated, options)
    |> deserialize(:"errors", :list, CrosslySellerAPI.Model.CreateAutomationRuleImportResponseErrors, options)
  end
end

