# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxAccrualPurchaseResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accrualId",
    :"duplicate",
    :"cents",
    :"rateBps",
    :"maturesAt",
    :"boostBudgetExhausted"
  ]

  @type t :: %__MODULE__{
    :"accrualId" => String.t | nil,
    :"duplicate" => boolean(),
    :"cents" => float(),
    :"rateBps" => float() | nil,
    :"maturesAt" => String.t | nil,
    :"boostBudgetExhausted" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxAccrualPurchaseResponse do
  def decode(value, _options) do
    value
  end
end

