# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateOrderRefundResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"refundId",
    :"amount"
  ]

  @type t :: %__MODULE__{
    :"refundId" => String.t,
    :"amount" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateOrderRefundResponse do
  def decode(value, _options) do
    value
  end
end

