# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxSubjectResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"subjectId",
    :"externalUserId",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"subjectId" => String.t,
    :"externalUserId" => String.t,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxSubjectResponse do
  def decode(value, _options) do
    value
  end
end

