# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateMagicScanResponsePossibleDuplicates do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"listingId",
    :"inventoryItemId",
    :"title",
    :"imageUrl",
    :"matchType",
    :"score",
    :"variationGroupId"
  ]

  @type t :: %__MODULE__{
    :"listingId" => String.t | nil,
    :"inventoryItemId" => String.t | nil,
    :"title" => String.t,
    :"imageUrl" => String.t | nil,
    :"matchType" => String.t,
    :"score" => float(),
    :"variationGroupId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateMagicScanResponsePossibleDuplicates do
  def decode(value, _options) do
    value
  end
end

