# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiExtractReceiptResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"error"
  ]

  @type t :: %__MODULE__{
    :"error" => CrosslySellerAPI.Model.CreateAiExtractReceiptResponseError.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiExtractReceiptResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"error", :struct, CrosslySellerAPI.Model.CreateAiExtractReceiptResponseError, options)
  end
end

