# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateBuyerOfferResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data"
  ]

  @type t :: %__MODULE__{
    :"data" => CrosslySellerAPI.Model.CreateBuyerOfferResponseData.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateBuyerOfferResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, CrosslySellerAPI.Model.CreateBuyerOfferResponseData, options)
  end
end

