# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiMagicListingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"suggestedPrice",
    :"priceRange",
    :"category",
    :"subCategory",
    :"brand",
    :"condition",
    :"colors",
    :"size",
    :"tags",
    :"suggestedTitle",
    :"material",
    :"style",
    :"pattern",
    :"department",
    :"gender",
    :"itemType",
    :"sizeSystem"
  ]

  @type t :: %__MODULE__{
    :"description" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"suggestedPrice" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseSuggestedPrice.t | nil,
    :"priceRange" => CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRange.t | nil,
    :"category" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"subCategory" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"brand" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"condition" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"colors" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseColors.t | nil,
    :"size" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"tags" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseColors.t | nil,
    :"suggestedTitle" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"material" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"style" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"pattern" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"department" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"gender" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"itemType" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil,
    :"sizeSystem" => CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiMagicListingResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"description", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"suggestedPrice", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseSuggestedPrice, options)
    |> deserialize(:"priceRange", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRange, options)
    |> deserialize(:"category", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"subCategory", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"brand", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"condition", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"colors", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseColors, options)
    |> deserialize(:"size", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"tags", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseColors, options)
    |> deserialize(:"suggestedTitle", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"material", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"style", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"pattern", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"department", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"gender", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"itemType", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
    |> deserialize(:"sizeSystem", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponseDescription, options)
  end
end

