# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateBuyerIdentifyResponseHudAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"kind",
    :"label",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"kind" => String.t,
    :"label" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateBuyerIdentifyResponseHudAction do
  def decode(value, _options) do
    value
  end
end

