# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateOrderPullPlatformLabelResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"persisted",
    :"expiresInSeconds",
    :"provenance"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t,
    :"persisted" => boolean(),
    :"expiresInSeconds" => float(),
    :"provenance" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateOrderPullPlatformLabelResponse do
  def decode(value, _options) do
    value
  end
end

