# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateNotificationIntegrationTestResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ok",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"ok" => boolean(),
    :"status" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateNotificationIntegrationTestResponse do
  def decode(value, _options) do
    value
  end
end

