# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxClaimSendResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"txSig",
    :"reason"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"txSig" => String.t | nil,
    :"reason" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxClaimSendResponse do
  def decode(value, _options) do
    value
  end
end

