# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxSubjectSpendPlanResponseLegs do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"source",
    :"baseUnits"
  ]

  @type t :: %__MODULE__{
    :"source" => String.t,
    :"baseUnits" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxSubjectSpendPlanResponseLegs do
  def decode(value, _options) do
    value
  end
end

