# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateWebhookResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"secret",
    :"id",
    :"createdAt",
    :"url",
    :"events",
    :"description",
    :"enabled"
  ]

  @type t :: %__MODULE__{
    :"secret" => String.t,
    :"id" => String.t,
    :"createdAt" => DateTime.t,
    :"url" => String.t,
    :"events" => [String.t],
    :"description" => String.t | nil,
    :"enabled" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateWebhookResponse do
  def decode(value, _options) do
    value
  end
end

