# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAutomationRuleImportResponseErrors do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"errors" => [map()]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAutomationRuleImportResponseErrors do
  def decode(value, _options) do
    value
  end
end

