# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRange do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"confidence"
  ]

  @type t :: %__MODULE__{
    :"value" => CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRangeValue.t,
    :"confidence" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRange do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"value", :struct, CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRangeValue, options)
  end
end

