# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateTeamAcceptResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ok",
    :"ownerUserId",
    :"role",
    :"scopes"
  ]

  @type t :: %__MODULE__{
    :"ok" => boolean(),
    :"ownerUserId" => String.t,
    :"role" => String.t,
    :"scopes" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateTeamAcceptResponse do
  def decode(value, _options) do
    value
  end
end

