# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateBuyerActivityResponseMatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"verdict",
    :"offer",
    :"savingCents",
    :"conditionComparable",
    :"shippingKnown",
    :"catalog",
    :"alternates"
  ]

  @type t :: %__MODULE__{
    :"verdict" => String.t,
    :"offer" => CrosslySellerAPI.Model.CreateBuyerActivityResponseMatchOffer.t,
    :"savingCents" => float() | nil,
    :"conditionComparable" => boolean(),
    :"shippingKnown" => boolean(),
    :"catalog" => CrosslySellerAPI.Model.GetCatalogLookupResponseCatalog.t | nil,
    :"alternates" => [CrosslySellerAPI.Model.CreateBuyerActivityResponseMatchOffer.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateBuyerActivityResponseMatch do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"offer", :struct, CrosslySellerAPI.Model.CreateBuyerActivityResponseMatchOffer, options)
    |> deserialize(:"catalog", :struct, CrosslySellerAPI.Model.GetCatalogLookupResponseCatalog, options)
    |> deserialize(:"alternates", :list, CrosslySellerAPI.Model.CreateBuyerActivityResponseMatchOffer, options)
  end
end

