# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"valid",
    :"error",
    :"details"
  ]

  @type t :: %__MODULE__{
    :"valid" => boolean(),
    :"error" => String.t,
    :"details" => CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetails.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :struct, CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetails, options)
  end
end

