# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiExtractReceiptResponseError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"code",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"code" => String.t,
    :"message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiExtractReceiptResponseError do
  def decode(value, _options) do
    value
  end
end

