# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateInboxCannedResponsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cannedResponse"
  ]

  @type t :: %__MODULE__{
    :"cannedResponse" => CrosslySellerAPI.Model.GetInboxCannedResponsResponseCannedResponses.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateInboxCannedResponsResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cannedResponse", :struct, CrosslySellerAPI.Model.GetInboxCannedResponsResponseCannedResponses, options)
  end
end

