# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"title",
    :"description",
    :"brand",
    :"grading",
    :"color",
    :"material",
    :"size",
    :"sizeSystem",
    :"weightOz",
    :"dimensions",
    :"priceCents",
    :"sellerNote",
    :"priceLowCents",
    :"priceMedianCents",
    :"priceHighCents",
    :"quantity",
    :"inventoryQuantity",
    :"unitsPerListing",
    :"costBasisCents",
    :"chosenDimensions",
    :"imageUrls",
    :"category",
    :"department",
    :"gender",
    :"style",
    :"pattern",
    :"itemType",
    :"upc",
    :"handlingTimeDays",
    :"returnWindowDays",
    :"tags",
    :"itemSpecifics",
    :"perPlatformOverrides",
    :"confidence",
    :"notes",
    :"sectionApplicability"
  ]

  @type t :: %__MODULE__{
    :"title" => String.t,
    :"description" => String.t,
    :"brand" => String.t | nil,
    :"grading" => CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadGrading.t | nil,
    :"color" => String.t | nil,
    :"material" => String.t | nil,
    :"size" => String.t | nil,
    :"sizeSystem" => String.t | nil,
    :"weightOz" => float() | nil,
    :"dimensions" => CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadDimensions.t | nil,
    :"priceCents" => float() | nil,
    :"sellerNote" => String.t | nil,
    :"priceLowCents" => float() | nil,
    :"priceMedianCents" => float() | nil,
    :"priceHighCents" => float() | nil,
    :"quantity" => float() | nil,
    :"inventoryQuantity" => float() | nil,
    :"unitsPerListing" => float() | nil,
    :"costBasisCents" => float() | nil,
    :"chosenDimensions" => CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadChosenDimensions.t | nil,
    :"imageUrls" => [String.t] | nil,
    :"category" => CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadCategory.t | nil,
    :"department" => String.t | nil,
    :"gender" => String.t | nil,
    :"style" => String.t | nil,
    :"pattern" => String.t | nil,
    :"itemType" => String.t | nil,
    :"upc" => String.t | nil,
    :"handlingTimeDays" => String.t | nil,
    :"returnWindowDays" => String.t | nil,
    :"tags" => [String.t] | nil,
    :"itemSpecifics" => String.t | nil,
    :"perPlatformOverrides" => map(),
    :"confidence" => float(),
    :"notes" => String.t | nil,
    :"sectionApplicability" => CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadSectionApplicability.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayload do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"grading", :struct, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadGrading, options)
    |> deserialize(:"dimensions", :struct, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadDimensions, options)
    |> deserialize(:"chosenDimensions", :struct, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadChosenDimensions, options)
    |> deserialize(:"category", :struct, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadCategory, options)
    |> deserialize(:"sectionApplicability", :struct, CrosslySellerAPI.Model.CreateMagicScanSynthesizeResponsePayloadSectionApplicability, options)
  end
end

