# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAccountResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"platform",
    :"accountSlot",
    :"proxyAssigned"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"platform" => String.t,
    :"accountSlot" => float(),
    :"proxyAssigned" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAccountResponse do
  def decode(value, _options) do
    value
  end
end

