# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxCreditRefreshResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"creditLineId",
    :"earnedLimitCents",
    :"stakeBonusCents",
    :"totalLimitCents",
    :"rateBps",
    :"termDays",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"creditLineId" => String.t,
    :"earnedLimitCents" => float(),
    :"stakeBonusCents" => float(),
    :"totalLimitCents" => float(),
    :"rateBps" => float(),
    :"termDays" => float(),
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxCreditRefreshResponse do
  def decode(value, _options) do
    value
  end
end

