# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"formErrors",
    :"fieldErrors"
  ]

  @type t :: %__MODULE__{
    :"formErrors" => [String.t],
    :"fieldErrors" => CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetails do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fieldErrors", :struct, CrosslySellerAPI.Model.CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors, options)
  end
end

