# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiGenerateListingResponseSuggestedPrice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"confidence"
  ]

  @type t :: %__MODULE__{
    :"value" => float(),
    :"confidence" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiGenerateListingResponseSuggestedPrice do
  def decode(value, _options) do
    value
  end
end

