# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxCampaignExecuteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paidCount",
    :"paidBaseUnits"
  ]

  @type t :: %__MODULE__{
    :"paidCount" => float(),
    :"paidBaseUnits" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxCampaignExecuteResponse do
  def decode(value, _options) do
    value
  end
end

