# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateBuyerIdentifyResponseVisualMatches do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"title",
    :"priceCents",
    :"imageUrl",
    :"score"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"title" => String.t,
    :"priceCents" => float(),
    :"imageUrl" => String.t | nil,
    :"score" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateBuyerIdentifyResponseVisualMatches do
  def decode(value, _options) do
    value
  end
end

