# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateCbxSpendResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"spendId",
    :"duplicate",
    :"baseUnitsSpent",
    :"skimTotalBaseUnits",
    :"skimEventsBaseUnits",
    :"skimPlatformBaseUnits",
    :"skimCappedByOrderFee",
    :"centsPerToken"
  ]

  @type t :: %__MODULE__{
    :"spendId" => String.t,
    :"duplicate" => boolean(),
    :"baseUnitsSpent" => String.t,
    :"skimTotalBaseUnits" => String.t,
    :"skimEventsBaseUnits" => String.t,
    :"skimPlatformBaseUnits" => String.t,
    :"skimCappedByOrderFee" => boolean(),
    :"centsPerToken" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateCbxSpendResponse do
  def decode(value, _options) do
    value
  end
end

