# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRangeValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"low",
    :"high"
  ]

  @type t :: %__MODULE__{
    :"low" => float(),
    :"high" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.CreateAiGenerateListingResponsePriceRangeValue do
  def decode(value, _options) do
    value
  end
end

