# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.DeleteConnectionEmailImapResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"success"
  ]

  @type t :: %__MODULE__{
    :"success" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.DeleteConnectionEmailImapResponse do
  def decode(value, _options) do
    value
  end
end

