# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetBuyerCatalogListingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"title",
    :"description",
    :"priceCents",
    :"compareAtCents",
    :"currency",
    :"status",
    :"available",
    :"quantityAvailable",
    :"condition",
    :"brand",
    :"size",
    :"color",
    :"categoryMain",
    :"categorySub",
    :"images",
    :"sellerUsername",
    :"sellerDisplayName",
    :"listedAt"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"title" => String.t,
    :"description" => String.t | nil,
    :"priceCents" => float(),
    :"compareAtCents" => float() | nil,
    :"currency" => String.t,
    :"status" => String.t,
    :"available" => boolean(),
    :"quantityAvailable" => float(),
    :"condition" => String.t | nil,
    :"brand" => String.t | nil,
    :"size" => String.t | nil,
    :"color" => [String.t] | nil,
    :"categoryMain" => String.t | nil,
    :"categorySub" => String.t | nil,
    :"images" => [String.t],
    :"sellerUsername" => String.t | nil,
    :"sellerDisplayName" => String.t | nil,
    :"listedAt" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetBuyerCatalogListingResponse do
  def decode(value, _options) do
    value
  end
end

