# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAnalyticBookkeepingResponsePlatformBreakdown do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platform",
    :"revenue",
    :"count",
    :"platformFees",
    :"netProfit"
  ]

  @type t :: %__MODULE__{
    :"platform" => String.t,
    :"revenue" => float(),
    :"count" => float(),
    :"platformFees" => float(),
    :"netProfit" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAnalyticBookkeepingResponsePlatformBreakdown do
  def decode(value, _options) do
    value
  end
end

