# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetConnectionHealthResponseBrowser do
  @moduledoc """
  What the browser itself last reported, when it has reported at all.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"observations",
    :"cookieCount",
    :"extensionVersion",
    :"observedAt",
    :"observedAgo"
  ]

  @type t :: %__MODULE__{
    :"observations" => [map()],
    :"cookieCount" => float(),
    :"extensionVersion" => String.t | nil,
    :"observedAt" => String.t,
    :"observedAgo" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetConnectionHealthResponseBrowser do
  def decode(value, _options) do
    value
  end
end

