# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetPlatformLimitResponseEbaySellingCap do
  @moduledoc """
  eBay-imposed monthly selling cap (quantity + $$) fetched from Trading API GetMyeBaySelling. These are HARD blocks — past them, `publishOffer` returns an error. Distinct from the free-tier `limit` (which is just a fee threshold). Null when seller has no caps (established accounts) or the Trading call failed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amountLimit",
    :"amountUsed",
    :"quantityLimit",
    :"quantityUsed",
    :"currency",
    :"fetchedAt"
  ]

  @type t :: %__MODULE__{
    :"amountLimit" => float() | nil,
    :"amountUsed" => float() | nil,
    :"quantityLimit" => float() | nil,
    :"quantityUsed" => float() | nil,
    :"currency" => String.t,
    :"fetchedAt" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetPlatformLimitResponseEbaySellingCap do
  def decode(value, _options) do
    value
  end
end

