# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetOrderEvidenceResponseSealAssessment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"verdict",
    :"reasons",
    :"headline"
  ]

  @type t :: %__MODULE__{
    :"verdict" => String.t,
    :"reasons" => [map()],
    :"headline" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetOrderEvidenceResponseSealAssessment do
  def decode(value, _options) do
    value
  end
end

