# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetSpatialSceneResponseBreakdowns do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"facet",
    :"distinct"
  ]

  @type t :: %__MODULE__{
    :"facet" => String.t,
    :"distinct" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetSpatialSceneResponseBreakdowns do
  def decode(value, _options) do
    value
  end
end

