# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAutomationRuleResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rule"
  ]

  @type t :: %__MODULE__{
    :"rule" => CrosslySellerAPI.Model.GetAutomationRuleResponseRule.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAutomationRuleResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"rule", :struct, CrosslySellerAPI.Model.GetAutomationRuleResponseRule, options)
  end
end

