# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetInboxConversationMessageResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"messages"
  ]

  @type t :: %__MODULE__{
    :"messages" => [CrosslySellerAPI.Model.GetInboxConversationMessageResponseMessages.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetInboxConversationMessageResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"messages", :list, CrosslySellerAPI.Model.GetInboxConversationMessageResponseMessages, options)
  end
end

