# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetSpatialPublicResponseProfile do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categorySlug",
    :"label",
    :"tagline",
    :"presentation",
    :"itemModelVariants",
    :"itemSize",
    :"containers",
    :"defaultGroupBy",
    :"defaultSortBy",
    :"gradedVariant"
  ]

  @type t :: %__MODULE__{
    :"categorySlug" => String.t,
    :"label" => String.t,
    :"tagline" => String.t,
    :"presentation" => String.t,
    :"itemModelVariants" => [String.t] | nil,
    :"itemSize" => CrosslySellerAPI.Model.GetSpatialPublicResponseProfileItemSize.t,
    :"containers" => [CrosslySellerAPI.Model.GetSpatialPublicResponseProfileContainers.t],
    :"defaultGroupBy" => [String.t],
    :"defaultSortBy" => [String.t],
    :"gradedVariant" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetSpatialPublicResponseProfile do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"itemSize", :struct, CrosslySellerAPI.Model.GetSpatialPublicResponseProfileItemSize, options)
    |> deserialize(:"containers", :list, CrosslySellerAPI.Model.GetSpatialPublicResponseProfileContainers, options)
  end
end

