# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAiProviderResponseProviders do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"label",
    :"supportsVision",
    :"supportsJsonMode",
    :"defaultTextModel",
    :"defaultVisionModel"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"label" => String.t,
    :"supportsVision" => boolean(),
    :"supportsJsonMode" => boolean(),
    :"defaultTextModel" => String.t,
    :"defaultVisionModel" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAiProviderResponseProviders do
  def decode(value, _options) do
    value
  end
end

