# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCustomerResponseContact do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"email",
    :"name",
    :"phone",
    :"address",
    :"addressPlatform"
  ]

  @type t :: %__MODULE__{
    :"email" => String.t | nil,
    :"name" => String.t | nil,
    :"phone" => String.t | nil,
    :"address" => CrosslySellerAPI.Model.GetCustomerResponseContactAddress.t | nil,
    :"addressPlatform" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCustomerResponseContact do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, CrosslySellerAPI.Model.GetCustomerResponseContactAddress, options)
  end
end

