# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCatalogLookupResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"identifier",
    :"offers"
  ]

  @type t :: %__MODULE__{
    :"identifier" => CrosslySellerAPI.Model.GetCatalogLookupResponseIdentifier.t,
    :"offers" => [CrosslySellerAPI.Model.GetCatalogLookupResponseOffers.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCatalogLookupResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"identifier", :struct, CrosslySellerAPI.Model.GetCatalogLookupResponseIdentifier, options)
    |> deserialize(:"offers", :list, CrosslySellerAPI.Model.GetCatalogLookupResponseOffers, options)
  end
end

