# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAnalyticDashboardResponseCancelRate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"current",
    :"previous"
  ]

  @type t :: %__MODULE__{
    :"current" => float(),
    :"previous" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAnalyticDashboardResponseCancelRate do
  def decode(value, _options) do
    value
  end
end

