# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetStyleResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"styles"
  ]

  @type t :: %__MODULE__{
    :"styles" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetStyleResponse do
  def decode(value, _options) do
    value
  end
end

