# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetTaxScheduleCResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"year",
    :"businessName",
    :"ein",
    :"address",
    :"grossReceipts",
    :"returnsAndAllowances",
    :"netSales",
    :"expenses",
    :"netProfit",
    :"counts"
  ]

  @type t :: %__MODULE__{
    :"year" => float(),
    :"businessName" => String.t | nil,
    :"ein" => String.t | nil,
    :"address" => String.t | nil,
    :"grossReceipts" => float(),
    :"returnsAndAllowances" => float(),
    :"netSales" => float(),
    :"expenses" => CrosslySellerAPI.Model.GetTaxScheduleCResponseExpenses.t,
    :"netProfit" => float(),
    :"counts" => CrosslySellerAPI.Model.GetTaxScheduleCResponseCounts.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetTaxScheduleCResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"expenses", :struct, CrosslySellerAPI.Model.GetTaxScheduleCResponseExpenses, options)
    |> deserialize(:"counts", :struct, CrosslySellerAPI.Model.GetTaxScheduleCResponseCounts, options)
  end
end

