# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetTeamResponseInvitations do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"pending",
    :"id",
    :"inviteeEmail",
    :"role",
    :"scopes",
    :"expiresAt",
    :"acceptedAt",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"pending" => boolean(),
    :"id" => String.t,
    :"inviteeEmail" => String.t,
    :"role" => String.t,
    :"scopes" => [String.t],
    :"expiresAt" => DateTime.t,
    :"acceptedAt" => DateTime.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetTeamResponseInvitations do
  def decode(value, _options) do
    value
  end
end

