# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetConnectionHealthResponseExtension do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"online",
    :"lastBrowserPushAt",
    :"lastBrowserPushAgo",
    :"reportedVersion"
  ]

  @type t :: %__MODULE__{
    :"online" => boolean(),
    :"lastBrowserPushAt" => String.t | nil,
    :"lastBrowserPushAgo" => String.t,
    :"reportedVersion" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetConnectionHealthResponseExtension do
  def decode(value, _options) do
    value
  end
end

