# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCbxCreditResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"totalLimitCents",
    :"drawnCents",
    :"availableCents",
    :"rateBps",
    :"termDays",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"totalLimitCents" => float(),
    :"drawnCents" => float(),
    :"availableCents" => float(),
    :"rateBps" => float(),
    :"termDays" => float(),
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCbxCreditResponse do
  def decode(value, _options) do
    value
  end
end

