# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platform",
    :"requiredFields"
  ]

  @type t :: %__MODULE__{
    :"platform" => String.t,
    :"requiredFields" => [CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponseRequiredFields.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"requiredFields", :list, CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponseRequiredFields, options)
  end
end

