# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAnalyticTodayResponseStreak do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"current",
    :"longest",
    :"lastActiveDate"
  ]

  @type t :: %__MODULE__{
    :"current" => float(),
    :"longest" => float(),
    :"lastActiveDate" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAnalyticTodayResponseStreak do
  def decode(value, _options) do
    value
  end
end

