# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetOrderProofOfDeliveryResponseScans do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"detail",
    :"date",
    :"location"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"detail" => String.t | nil,
    :"date" => String.t | nil,
    :"location" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetOrderProofOfDeliveryResponseScans do
  def decode(value, _options) do
    value
  end
end

