# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetPatScopeResponseScopes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"label",
    :"description"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"label" => String.t,
    :"description" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetPatScopeResponseScopes do
  def decode(value, _options) do
    value
  end
end

