# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetOrderEvidenceResponseArrival do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"state",
    :"windowHours",
    :"requestedAt",
    :"closesAt",
    :"detail",
    :"photos"
  ]

  @type t :: %__MODULE__{
    :"state" => String.t,
    :"windowHours" => float(),
    :"requestedAt" => DateTime.t | nil,
    :"closesAt" => DateTime.t | nil,
    :"detail" => String.t,
    :"photos" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetOrderEvidenceResponseArrival do
  def decode(value, _options) do
    value
  end
end

