# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetBuyerPreferenceResponsePriceBand do
  @moduledoc """
  The band they actually shop in, from retail prices they were looking at.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"p25Cents",
    :"medianCents",
    :"p75Cents"
  ]

  @type t :: %__MODULE__{
    :"p25Cents" => float(),
    :"medianCents" => float(),
    :"p75Cents" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetBuyerPreferenceResponsePriceBand do
  def decode(value, _options) do
    value
  end
end

