# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCbxSubjectWalletResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"walletId",
    :"address",
    :"chain",
    :"verifiedAt"
  ]

  @type t :: %__MODULE__{
    :"walletId" => String.t,
    :"address" => String.t,
    :"chain" => String.t,
    :"verifiedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCbxSubjectWalletResponse do
  def decode(value, _options) do
    value
  end
end

