# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetSpatialPublicResponseProfileContainers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"label",
    :"model",
    :"size",
    :"slots"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"label" => String.t,
    :"model" => String.t,
    :"size" => map(),
    :"slots" => map()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetSpatialPublicResponseProfileContainers do
  def decode(value, _options) do
    value
  end
end

