# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAnalyticDashboardResponseTopCategories do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"count",
    :"revenue"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"count" => float(),
    :"revenue" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAnalyticDashboardResponseTopCategories do
  def decode(value, _options) do
    value
  end
end

