# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAccountDeletionStatusResponsePending do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"requestedAt",
    :"scheduledFor"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"requestedAt" => DateTime.t,
    :"scheduledFor" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAccountDeletionStatusResponsePending do
  def decode(value, _options) do
    value
  end
end

