# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetOauthInitResponseOneOf2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"oneShot"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t,
    :"oneShot" => boolean()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetOauthInitResponseOneOf2 do
  def decode(value, _options) do
    value
  end
end

