# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetPatScopeResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"scopes"
  ]

  @type t :: %__MODULE__{
    :"scopes" => [CrosslySellerAPI.Model.GetPatScopeResponseScopes.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetPatScopeResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"scopes", :list, CrosslySellerAPI.Model.GetPatScopeResponseScopes, options)
  end
end

