# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetMagicDraftResponseDraft do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"createdAt",
    :"userId",
    :"listingId",
    :"runId",
    :"selectedMatchKeys",
    :"chosenPriceCents",
    :"chosenQuantity",
    :"chosenCondition"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"createdAt" => DateTime.t,
    :"userId" => String.t,
    :"listingId" => String.t | nil,
    :"runId" => String.t,
    :"selectedMatchKeys" => [String.t] | nil,
    :"chosenPriceCents" => float() | nil,
    :"chosenQuantity" => float() | nil,
    :"chosenCondition" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetMagicDraftResponseDraft do
  def decode(value, _options) do
    value
  end
end

