# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetWorkflowChainResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"chain",
    :"steps"
  ]

  @type t :: %__MODULE__{
    :"chain" => CrosslySellerAPI.Model.GetWorkflowChainResponseChain.t,
    :"steps" => [CrosslySellerAPI.Model.ListWorkflowChainsItemSteps.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetWorkflowChainResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"chain", :struct, CrosslySellerAPI.Model.GetWorkflowChainResponseChain, options)
    |> deserialize(:"steps", :list, CrosslySellerAPI.Model.ListWorkflowChainsItemSteps, options)
  end
end

