# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCustomerResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"normalizedHandle",
    :"platforms",
    :"totalOrders",
    :"totalSpent",
    :"orders",
    :"contact"
  ]

  @type t :: %__MODULE__{
    :"normalizedHandle" => String.t,
    :"platforms" => [String.t],
    :"totalOrders" => float(),
    :"totalSpent" => float(),
    :"orders" => [CrosslySellerAPI.Model.GetCustomerResponseOrders.t],
    :"contact" => CrosslySellerAPI.Model.GetCustomerResponseContact.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCustomerResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"orders", :list, CrosslySellerAPI.Model.GetCustomerResponseOrders, options)
    |> deserialize(:"contact", :struct, CrosslySellerAPI.Model.GetCustomerResponseContact, options)
  end
end

