# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetBuyerScanSessionResponseCaptures do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"matchMethod",
    :"identifier",
    :"verdict",
    :"displayLine",
    :"savingCents",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"matchMethod" => String.t,
    :"identifier" => CrosslySellerAPI.Model.GetBuyerScanSessionResponseIdentifier.t | nil,
    :"verdict" => String.t,
    :"displayLine" => String.t | nil,
    :"savingCents" => float() | nil,
    :"createdAt" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetBuyerScanSessionResponseCaptures do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"identifier", :struct, CrosslySellerAPI.Model.GetBuyerScanSessionResponseIdentifier, options)
  end
end

