# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetListingVariationGroupResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"group"
  ]

  @type t :: %__MODULE__{
    :"group" => CrosslySellerAPI.Model.GetListingVariationGroupResponseGroup.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetListingVariationGroupResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"group", :struct, CrosslySellerAPI.Model.GetListingVariationGroupResponseGroup, options)
  end
end

