# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAutomationRuleExportResponseCondition do
  @moduledoc """
  Omit or set `type: 'none'` to fire on every match.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"config"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"config" => map()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAutomationRuleExportResponseCondition do
  def decode(value, _options) do
    value
  end
end

