# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetMarketProductResponseProduct do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"brand",
    :"name",
    :"createdAt",
    :"status",
    :"retailCents",
    :"categorySlug",
    :"externalId",
    :"imageUrl",
    :"model",
    :"colorway",
    :"styleCode",
    :"releaseDate",
    :"submittedByUserId",
    :"approvedByUserId",
    :"approvedAt",
    :"rejectionReason",
    :"proposedVariants",
    :"verification",
    :"aiVerdict",
    :"submissionSource",
    :"duplicateOfSkuId",
    :"preferredProviderSlug",
    :"allowPreBid",
    :"preBidOpensAt",
    :"featured",
    :"externalSource",
    :"externalSyncedAt",
    :"gradedGradeKeys",
    :"lowestAskCents",
    :"highestBidCents",
    :"lastSaleCents",
    :"tradesCount"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"brand" => String.t | nil,
    :"name" => String.t,
    :"createdAt" => DateTime.t,
    :"status" => String.t,
    :"retailCents" => float() | nil,
    :"categorySlug" => String.t,
    :"externalId" => String.t | nil,
    :"imageUrl" => String.t | nil,
    :"model" => String.t | nil,
    :"colorway" => String.t | nil,
    :"styleCode" => String.t | nil,
    :"releaseDate" => String.t | nil,
    :"submittedByUserId" => String.t | nil,
    :"approvedByUserId" => String.t | nil,
    :"approvedAt" => DateTime.t | nil,
    :"rejectionReason" => String.t | nil,
    :"proposedVariants" => [CrosslySellerAPI.Model.GetMarketProductResponseProductProposedVariants.t],
    :"verification" => map(),
    :"aiVerdict" => map() | nil,
    :"submissionSource" => String.t | nil,
    :"duplicateOfSkuId" => String.t | nil,
    :"preferredProviderSlug" => String.t | nil,
    :"allowPreBid" => boolean(),
    :"preBidOpensAt" => DateTime.t | nil,
    :"featured" => boolean(),
    :"externalSource" => String.t | nil,
    :"externalSyncedAt" => DateTime.t | nil,
    :"gradedGradeKeys" => [String.t],
    :"lowestAskCents" => float() | nil,
    :"highestBidCents" => float() | nil,
    :"lastSaleCents" => float() | nil,
    :"tradesCount" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetMarketProductResponseProduct do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"proposedVariants", :list, CrosslySellerAPI.Model.GetMarketProductResponseProductProposedVariants, options)
  end
end

