# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetMileageSummaryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"year",
    :"ratePerMile",
    :"totalMiles",
    :"deduction",
    :"entryCount"
  ]

  @type t :: %__MODULE__{
    :"year" => float(),
    :"ratePerMile" => float(),
    :"totalMiles" => float(),
    :"deduction" => float(),
    :"entryCount" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetMileageSummaryResponse do
  def decode(value, _options) do
    value
  end
end

