# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponseRequiredFields do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"label",
    :"master",
    :"required",
    :"dataType",
    :"hasEnumValues",
    :"enumValues",
    :"hint"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"label" => String.t,
    :"master" => boolean(),
    :"required" => boolean(),
    :"dataType" => String.t,
    :"hasEnumValues" => boolean(),
    :"enumValues" => [String.t] | nil,
    :"hint" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetTaxonomyRequiredFieldResponseRequiredFields do
  def decode(value, _options) do
    value
  end
end

