# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetBuyerPreferenceResponseBrands do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"brand",
    :"looks"
  ]

  @type t :: %__MODULE__{
    :"brand" => String.t,
    :"looks" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetBuyerPreferenceResponseBrands do
  def decode(value, _options) do
    value
  end
end

