# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetBuyerCatalogListingAvailabilityResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"available",
    :"quantityAvailable",
    :"priceCents",
    :"currency",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"available" => boolean(),
    :"quantityAvailable" => float(),
    :"priceCents" => float(),
    :"currency" => String.t,
    :"status" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetBuyerCatalogListingAvailabilityResponse do
  def decode(value, _options) do
    value
  end
end

