# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetCbxTreasuryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"takenAt",
    :"coverageBps",
    :"ok",
    :"reserveBaseUnits",
    :"outstandingBaseUnits",
    :"inFlightClaimBaseUnits",
    :"notes"
  ]

  @type t :: %__MODULE__{
    :"takenAt" => DateTime.t,
    :"coverageBps" => float(),
    :"ok" => boolean(),
    :"reserveBaseUnits" => String.t,
    :"outstandingBaseUnits" => String.t,
    :"inFlightClaimBaseUnits" => String.t,
    :"notes" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetCbxTreasuryResponse do
  def decode(value, _options) do
    value
  end
end

