# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetConnectionHealthResponseAccounts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"platformName",
    :"accountId",
    :"accountSlot",
    :"label",
    :"platformUsername",
    :"summary",
    :"action",
    :"liveness",
    :"browser",
    :"platform",
    :"state",
    :"severity",
    :"audience",
    :"anchors",
    :"notes"
  ]

  @type t :: %__MODULE__{
    :"platformName" => String.t,
    :"accountId" => String.t | nil,
    :"accountSlot" => float() | nil,
    :"label" => String.t | nil,
    :"platformUsername" => String.t | nil,
    :"summary" => String.t,
    :"action" => String.t,
    :"liveness" => CrosslySellerAPI.Model.GetConnectionHealthResponseLiveness.t,
    :"browser" => CrosslySellerAPI.Model.GetConnectionHealthResponseBrowser.t | nil,
    :"platform" => String.t,
    :"state" => String.t,
    :"severity" => String.t,
    :"audience" => String.t,
    :"anchors" => CrosslySellerAPI.Model.GetConnectionHealthResponseAnchors.t | nil,
    :"notes" => [String.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetConnectionHealthResponseAccounts do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"liveness", :struct, CrosslySellerAPI.Model.GetConnectionHealthResponseLiveness, options)
    |> deserialize(:"browser", :struct, CrosslySellerAPI.Model.GetConnectionHealthResponseBrowser, options)
    |> deserialize(:"anchors", :struct, CrosslySellerAPI.Model.GetConnectionHealthResponseAnchors, options)
  end
end

