# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetConnectionEmailResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"imap",
    :"oauth"
  ]

  @type t :: %__MODULE__{
    :"data" => [CrosslySellerAPI.Model.GetConnectionEmailResponseData.t],
    :"imap" => [CrosslySellerAPI.Model.GetConnectionEmailResponseData.t],
    :"oauth" => [CrosslySellerAPI.Model.GetConnectionEmailResponseOauth.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetConnectionEmailResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, CrosslySellerAPI.Model.GetConnectionEmailResponseData, options)
    |> deserialize(:"imap", :list, CrosslySellerAPI.Model.GetConnectionEmailResponseData, options)
    |> deserialize(:"oauth", :list, CrosslySellerAPI.Model.GetConnectionEmailResponseOauth, options)
  end
end

