# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAnalyticBookkeepingResponseMonthlyPl do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"month",
    :"revenue",
    :"cogs",
    :"platformFees",
    :"shippingCosts",
    :"netProfit"
  ]

  @type t :: %__MODULE__{
    :"month" => float(),
    :"revenue" => float(),
    :"cogs" => float(),
    :"platformFees" => float(),
    :"shippingCosts" => float(),
    :"netProfit" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAnalyticBookkeepingResponseMonthlyPl do
  def decode(value, _options) do
    value
  end
end

