# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetAutomationRuleExportByIdResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"action",
    :"trigger",
    :"schemaVersion",
    :"condition",
    :"metadata",
    :"description",
    :"platforms",
    :"$schema"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"action" => CrosslySellerAPI.Model.GetAutomationRuleExportResponseAction.t,
    :"trigger" => CrosslySellerAPI.Model.GetAutomationRuleExportResponseAction.t,
    :"schemaVersion" => float(),
    :"condition" => CrosslySellerAPI.Model.GetAutomationRuleExportResponseCondition.t | nil,
    :"metadata" => CrosslySellerAPI.Model.GetAutomationRuleExportResponseMetadata.t | nil,
    :"description" => String.t | nil,
    :"platforms" => [String.t] | nil,
    :"$schema" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetAutomationRuleExportByIdResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"action", :struct, CrosslySellerAPI.Model.GetAutomationRuleExportResponseAction, options)
    |> deserialize(:"trigger", :struct, CrosslySellerAPI.Model.GetAutomationRuleExportResponseAction, options)
    |> deserialize(:"condition", :struct, CrosslySellerAPI.Model.GetAutomationRuleExportResponseCondition, options)
    |> deserialize(:"metadata", :struct, CrosslySellerAPI.Model.GetAutomationRuleExportResponseMetadata, options)
  end
end

