# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetOrderShipmentResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"createdAt",
    :"userId",
    :"source",
    :"orderId",
    :"carrier",
    :"service",
    :"trackingNumber",
    :"voidedAt",
    :"labelCostCents",
    :"labelUrl",
    :"shippoShipmentId",
    :"trackingRegisteredAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"createdAt" => DateTime.t,
    :"userId" => String.t,
    :"source" => String.t,
    :"orderId" => String.t,
    :"carrier" => String.t | nil,
    :"service" => String.t | nil,
    :"trackingNumber" => String.t | nil,
    :"voidedAt" => DateTime.t | nil,
    :"labelCostCents" => float() | nil,
    :"labelUrl" => String.t | nil,
    :"shippoShipmentId" => String.t | nil,
    :"trackingRegisteredAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetOrderShipmentResponseData do
  def decode(value, _options) do
    value
  end
end

