# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetTeamResponseMembers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"memberUserId",
    :"memberEmail",
    :"memberDisplayName",
    :"role",
    :"scopes",
    :"revokedAt",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"memberUserId" => String.t,
    :"memberEmail" => String.t | nil,
    :"memberDisplayName" => String.t | nil,
    :"role" => String.t,
    :"scopes" => [String.t],
    :"revokedAt" => DateTime.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetTeamResponseMembers do
  def decode(value, _options) do
    value
  end
end

