# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.GetConnectionEmailResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"type",
    :"isConnected",
    :"email",
    :"host",
    :"port",
    :"lastSyncedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"type" => String.t,
    :"isConnected" => boolean(),
    :"email" => String.t,
    :"host" => String.t | nil,
    :"port" => float() | nil,
    :"lastSyncedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.GetConnectionEmailResponseData do
  def decode(value, _options) do
    value
  end
end

