# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.InlineObject3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"allowedOrigins",
    :"environment"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"allowedOrigins" => [String.t] | nil,
    :"environment" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.InlineObject3 do
  def decode(value, _options) do
    value
  end
end

