# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.InlineObject2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"action",
    :"counterCents"
  ]

  @type t :: %__MODULE__{
    :"action" => String.t,
    :"counterCents" => integer() | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.InlineObject2 do
  def decode(value, _options) do
    value
  end
end

