# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListConnectionsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"platform",
    :"isActive",
    :"shopUrl",
    :"lastSeenActive",
    :"tokenExpiresAt",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"platform" => String.t,
    :"isActive" => boolean(),
    :"shopUrl" => String.t | nil,
    :"lastSeenActive" => DateTime.t | nil,
    :"tokenExpiresAt" => DateTime.t | nil,
    :"createdAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListConnectionsItem do
  def decode(value, _options) do
    value
  end
end

