# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListPatItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"prefix",
    :"scopes",
    :"environment",
    :"lastUsedAt",
    :"expiresAt",
    :"revokedAt",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"prefix" => String.t,
    :"scopes" => [String.t],
    :"environment" => String.t,
    :"lastUsedAt" => DateTime.t | nil,
    :"expiresAt" => DateTime.t | nil,
    :"revokedAt" => DateTime.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListPatItem do
  def decode(value, _options) do
    value
  end
end

