# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListListingsItemGrading do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"graderSlug",
    :"grade",
    :"qualifier",
    :"sealGrade",
    :"certNumber",
    :"gradeKey",
    :"verifiedAt"
  ]

  @type t :: %__MODULE__{
    :"graderSlug" => String.t,
    :"grade" => String.t,
    :"qualifier" => String.t | nil,
    :"sealGrade" => String.t | nil,
    :"certNumber" => String.t | nil,
    :"gradeKey" => String.t,
    :"verifiedAt" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListListingsItemGrading do
  def decode(value, _options) do
    value
  end
end

