# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListMileageItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"date",
    :"id",
    :"createdAt",
    :"userId",
    :"notes",
    :"miles",
    :"purpose",
    :"startLocation",
    :"endLocation"
  ]

  @type t :: %__MODULE__{
    :"date" => String.t,
    :"id" => String.t,
    :"createdAt" => DateTime.t,
    :"userId" => String.t,
    :"notes" => String.t | nil,
    :"miles" => String.t,
    :"purpose" => String.t,
    :"startLocation" => String.t | nil,
    :"endLocation" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListMileageItem do
  def decode(value, _options) do
    value
  end
end

