# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListSourcingDemandItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"namespace",
    :"identifierValue",
    :"looks",
    :"misses",
    :"retailers",
    :"medianPageCents",
    :"lastSeenAt"
  ]

  @type t :: %__MODULE__{
    :"namespace" => String.t,
    :"identifierValue" => String.t,
    :"looks" => float(),
    :"misses" => float(),
    :"retailers" => float(),
    :"medianPageCents" => float() | nil,
    :"lastSeenAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListSourcingDemandItem do
  def decode(value, _options) do
    value
  end
end

