# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListInventoryUnitsItemIdentifiers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"namespace",
    :"value",
    :"source",
    :"recordedAt",
    :"strength"
  ]

  @type t :: %__MODULE__{
    :"namespace" => String.t,
    :"value" => String.t,
    :"source" => String.t,
    :"recordedAt" => DateTime.t,
    :"strength" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListInventoryUnitsItemIdentifiers do
  def decode(value, _options) do
    value
  end
end

