# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListCbxSubjectGrantsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"kind",
    :"baseUnits",
    :"remainingBaseUnits",
    :"expiresAt",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"kind" => String.t,
    :"baseUnits" => String.t,
    :"remainingBaseUnits" => String.t,
    :"expiresAt" => String.t | nil,
    :"createdAt" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListCbxSubjectGrantsItem do
  def decode(value, _options) do
    value
  end
end

