# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListVariationGroupsItemRollup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"memberCount",
    :"fromPriceCents",
    :"status",
    :"availableUnits",
    :"needsAttention"
  ]

  @type t :: %__MODULE__{
    :"memberCount" => float(),
    :"fromPriceCents" => float() | nil,
    :"status" => String.t,
    :"availableUnits" => float(),
    :"needsAttention" => float()
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListVariationGroupsItemRollup do
  def decode(value, _options) do
    value
  end
end

