# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListVariationGroupsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"members",
    :"rollup",
    :"id",
    :"title"
  ]

  @type t :: %__MODULE__{
    :"members" => [CrosslySellerAPI.Model.ListVariationGroupsItemMembers.t],
    :"rollup" => CrosslySellerAPI.Model.ListVariationGroupsItemRollup.t,
    :"id" => String.t,
    :"title" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListVariationGroupsItem do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"members", :list, CrosslySellerAPI.Model.ListVariationGroupsItemMembers, options)
    |> deserialize(:"rollup", :struct, CrosslySellerAPI.Model.ListVariationGroupsItemRollup, options)
  end
end

