# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListBuyerCatalogSearchItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"title",
    :"priceCents",
    :"compareAtCents",
    :"currency",
    :"condition",
    :"brand",
    :"categoryMain",
    :"categorySub",
    :"thumbnail",
    :"images",
    :"sellerUsername",
    :"sellerDisplayName",
    :"quantityAvailable",
    :"listedAt",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"title" => String.t,
    :"priceCents" => float(),
    :"compareAtCents" => float() | nil,
    :"currency" => String.t,
    :"condition" => String.t | nil,
    :"brand" => String.t | nil,
    :"categoryMain" => String.t | nil,
    :"categorySub" => String.t | nil,
    :"thumbnail" => String.t | nil,
    :"images" => [String.t],
    :"sellerUsername" => String.t | nil,
    :"sellerDisplayName" => String.t | nil,
    :"quantityAvailable" => float(),
    :"listedAt" => String.t | nil,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListBuyerCatalogSearchItem do
  def decode(value, _options) do
    value
  end
end

