# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.ListBuyerWishlistItemsItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"platformListingId",
    :"addedAt",
    :"slug",
    :"title"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"platformListingId" => String.t,
    :"addedAt" => DateTime.t,
    :"slug" => String.t | nil,
    :"title" => String.t | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.ListBuyerWishlistItemsItem do
  def decode(value, _options) do
    value
  end
end

