# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.UpdateAutomationRuleResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rule"
  ]

  @type t :: %__MODULE__{
    :"rule" => map() | nil
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.UpdateAutomationRuleResponse do
  def decode(value, _options) do
    value
  end
end

