# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule CrosslySellerAPI.Model.UpdateListingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"jobs"
  ]

  @type t :: %__MODULE__{
    :"jobs" => [CrosslySellerAPI.Model.CreateListingResponseJobs.t]
  }
end

defimpl Poison.Decoder, for: CrosslySellerAPI.Model.UpdateListingResponse do
  import CrosslySellerAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"jobs", :list, CrosslySellerAPI.Model.CreateListingResponseJobs, options)
  end
end

